---
title: "mult_imp_mice_ANES"
author: "Xiaoran Sun"
date: "2018/11/18"
output: html_document
---

```{r}
setwd("~/Desktop/paper/SODA501/project/github/MIML/ANES") #Xiaoran's working directory
library(mice)
library(xtable)
load("cleanedANES.RData")
names(anes)
```

```{r}
#transfer type of binary & categorical data into factor (from numeric)
for(i in c(1:4, 7:14)){
  anes[,i]<-as.factor(anes[,i])
}
str(anes)
```


```{r}
#imputation method for each variable
impmethod<-c("logreg", "logreg", "logreg", "polr", "pmm", "pmm", "polr", "polr", "polr", "polr", "logreg", "logreg", "logreg", "logreg")
tempData <- mice(anes,m=5,maxit=100,meth=impmethod,seed=500)
summary(tempData)
save(tempData, file="tempData_imp_mice_anes.RData")
```

Run regression models
```{r}
load("tempData_imp_mice_anes.RData")
# Model vote choice w/o feeling thermometers (reduce collinearity w/ ideology)
vote.dem.noFT <- with(tempData, glm(vote.dem ~ dem + gop + as.numeric(ideo) + as.numeric(bible) + as.numeric(inform) + as.numeric(edu) +  as.numeric(income) + female + black + hisp, family = 'binomial'))
model1<-round(summary(pool(vote.dem.noFT)),4)
mean(c(vote.dem.noFT$analyses[[1]]$deviance, vote.dem.noFT$analyses[[2]]$deviance, vote.dem.noFT$analyses[[3]]$deviance, vote.dem.noFT$analyses[[4]]$deviance, vote.dem.noFT$analyses[[5]]$deviance))

mean(c(vote.dem.noFT$analyses[[1]]$aic, vote.dem.noFT$analyses[[2]]$aic, vote.dem.noFT$analyses[[3]]$aic, vote.dem.noFT$analyses[[4]]$aic, vote.dem.noFT$analyses[[5]]$aic))

mice_vote.dem.noFT<-model1
save(mice_vote.dem.noFT, file="model output/mice_vote.dem.noFT.RData")
```

```{r}
# Model feeling thermometer for Trump (0-100 treated as continuous)
trump.FT <-with(tempData, lm(DJT.FT ~ dem + gop + as.numeric(ideo) + as.numeric(bible) + as.numeric(inform) + as.numeric(edu) +  as.numeric(income) + female + black + hisp))
model2<-round(summary(pool(trump.FT)),4)
pool.r.squared(trump.FT)
pool.r.squared(trump.FT, adjusted=TRUE)

mice_trump.FT<-model2
save(mice_trump.FT, file="model output/mice_trump.FT.RData")
```

```{r}
xtable(model1)
xtable(model2)
```