---
title: "MIML_KNN"
---
## So Young Park

This script applies multiple imputation w/ k nearest neighbors (KNN) approach to ANES data


```{r}
# Clear workspace
rm(list = ls())

# Load packages
library(dplyr)
library(data.table)
library(Amelia)
library(VIM)
```

```{r load data}
# Load ANES data.
load("C:/Users/soyou/Box Sync/GitHub/MIML/ANES/cleanedANES.RData")

### Check number of NA's per row
sum_nacount <- apply(anes, 1, function(x) sum(is.na(x)))
length(which(sum_nacount>1))

# Exploratory analysis:
aggr(anes, prop = T, numbers = T, main = "Missing values vs observed, Full Data")

dim(anes)
anes.complete <-anes[complete.cases(anes)]
dim(anes.complete) #deletes 1889 rows
anes <- as.data.frame(anes)

# Specify variable type
cols1 <- c("vote.dem", "dem", "gop", "female", "black", "hisp", "white") # categorical
cols2 <- c("ideo", "bible", "inform", "edu", "income") # ordinal

# Use lapply() to coerce and replace the chosen columns to factors:
anes[cols1] <- lapply(anes[cols1], factor)
anes[cols2] <- lapply(anes[cols2], ordered)
```

```{r imputation}
# Imputation using VIM::kNN

anes.knn <- VIM::kNN(anes, k = 5, weights = NULL, numFun = median, catFun = maxCat, impNA = TRUE, trace = TRUE, imp_var = TRUE, imp_suffix = "imp", addRandom = FALSE, useImputedDist = TRUE, weightDist = FALSE) #median

#anes.knn2 <- VIM::kNN(anes, k = 5, weights = NULL, numFun = median, catFun = maxCat, makeNA = NULL, NAcond = NULL, impNA = TRUE, donorcond = NULL, mixed = vector(), mixed.constant = NULL, trace = FALSE, imp_var = TRUE, imp_suffix = "imp", addRandom = FALSE, useImputedDist = TRUE, weightDist = FALSE) #mean

#check to make sure there are no missing values
length(which(is.na(anes.knn)))
```

```{r regression}
# With the imputed dataset, I run two regressions:  logit and OLS.

anes.knn <- anes.knn[1:14]
#change categorical back to continuous

# Use lapply() to coerce and replace the chosen columns to factors:
anes.knn[cols2] <- lapply(anes.knn[cols2], as.numeric)
anes[cols2] <- lapply(anes[cols2], as.numeric)

# Logit:
## Model vote choice w/o feeling thermometers (reduce collinearity w/ ideology) ##
# vote.dem.noFT <- glm(vote.dem ~ dem + gop + ideo + bible + inform + edu + 
#                          income + female + black + hisp, data = ANES.svm$ximp, family = 'binomial')
# summary(vote.dem.noFT)
logit_form <- as.formula(vote.dem ~ dem + gop + ideo + bible + inform + edu + 
                           income + female + black + hisp)

logit_knn <- glm(logit_form, data = anes.knn, family="binomial")
logit_full <- glm(logit_form, data = anes, family=binomial(link='logit'))

# OLS:
# Model feeling thermometer for Trump (0-100 treated as continuous)
ols_form <- as.formula(DJT.FT ~ dem + gop + ideo + bible + inform + edu + income + female + black + hisp)
ols_knn <- lm(ols_form, data = anes.knn)
ols_full <- lm(ols_form, data = anes)

ols_list <- list(ols_knn, ols_full)
logit_list <- list(logit_knn, logit_full)

save(logit_list, ols_list, file = "C:/Users/soyou/Box Sync/Classes/2018 Fall/SoDA 502/ANES_knn.RData")
```
